apiVersion: hana.orchestrate.cloud.sap/v1alpha1
kind: ProviderConfigUsage
metadata:
  name: example-providerconfigusage
providerConfigRef:
  name: example
resourceRef:
  apiVersion: schema.hana.orchestrate.cloud.sap/v1alpha1
  kind: DbSchema
  name: example-dbschema