apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
data:
  # Dummy credentials. Replace with real credentials.
  endpoint: aHR0cDovL2hhbmEtZXhhbXBsZS1lbmRwb2ludC5jb20=
  password: cGFzc3dvcmQ=
  port: NDMyMQ==
  username: dXNlcg==
---
apiVersion: hana.sap.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    connectionSecretRef:
      name: example-provider-secret
      namespace: crossplane-system
