# Enviroment variables/secrets that are needed
# More information in the README.md

name: e2e-Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      checkout-ref:
        description: 'the ref for the repo checkout step'
        default: ''
        required: false
        type: string
      environment:
        description: 'the environment to run in'
        default: 'pr-e2e-approval'
        required: false
        type: string
    secrets:
      HANA_BINDINGS:
        required: true

permissions:
  contents: read
  actions: read  # Needed for Turnstyle to query workflow runs

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          #use inputs.checkout-ref to be able to call it from a pull_request_target workflow, since there it needs to be github.event.pull_request.head.sha and not the default
          ref: ${{ inputs.checkout-ref }}
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26'

      - name: Wait for other e2e tests on shared HANA DB
        uses: softprops/turnstyle@v3
        with:
          same-branch-only: false
          abort-after-seconds: 7200

      - name: Run build and e2e test
        run: make e2e.run
        env:
          HANA_BINDINGS: ${{ secrets.HANA_BINDINGS }}
