# Enviroment variables/secrets that are needed
# CF_CREDENTIALS contains the login information of the CF technical user for this test
# CF_ENVIRONMENT contains the URL of the CF API endpoint
# USER_WHERE_ROLES_GET_ASSIGNED_EMAIL contains the email of a technical user (different to TECHNICAL_USER_EMAIL)
# TECHNICAL_USER_EMAIL contains the email of the BTP_TECHNICAL_USER
# More information in the README.md

name: e2e-Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      checkout-ref:
        description: 'the ref for the repo checkout step'
        default: ''
        required: false
        type: string
      environment:
        description: 'the environment to run in'
        default: 'pr-e2e-approval'
        required: false
        type: string
    secrets:
      HANA_BINDINGS:
        description: contains the HANA service bindings in json format
        required: true
permissions:
  contents: read

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          #use inputs.checkout-ref to be able to call it from a pull_request_target workflow, since there it needs to be github.event.pull_request.head.sha and not the default
          ref: ${{ inputs.checkout-ref }}
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.24'

      - name: Run build and e2e test
        run: make e2e.run
        env:
          HANA_BINDINGS: ${{ secrets.CF_CREDENTIALS }}
