# This workflow is triggered by the user and runs the REUSE compliance check (reuse lint) on the repository.

name: REUSE Compliance Check

on:
  workflow_dispatch:
  workflow_call:


jobs:
  lint-reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0
